In [99]:
import pandas as pd
import numpy as np

In [100]:
cafe = pd.read_csv('dirty_cafe_sales (2).csv')

In [101]:
cafe.head()

Transaction ID    Item Quantity Price Per Unit Total Spent  Payment Method  \
0    TXN_1961373  Coffee        2            2.0         4.0     Credit Card   
1    TXN_4977031    Cake        4            3.0        12.0            Cash   
2    TXN_4271903  Cookie        4            1.0       ERROR     Credit Card   
3    TXN_7034554   Salad        2            5.0        10.0         UNKNOWN   
4    TXN_3160411  Coffee        2            2.0         4.0  Digital Wallet   

   Location Transaction Date  
0  Takeaway       2023-09-08  
1  In-store       2023-05-16  
2  In-store       2023-07-19  
3   UNKNOWN       2023-04-27  
4  In-store       2023-06-11

In [102]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB


In [103]:
cafe.shape

(10000, 8)

In [104]:
cafe.describe()

Transaction ID   Item Quantity Price Per Unit Total Spent  \
count           10000   9667     9862           9821        9827   
unique          10000     10        7              8          19   
top       TXN_1961373  Juice        5            3.0         6.0   
freq                1   1171     2013           2429         979   

        Payment Method  Location Transaction Date  
count             7421      6735             9841  
unique               5         4              367  
top     Digital Wallet  Takeaway          UNKNOWN  
freq              2291      3022              159

In [105]:
cafe.dtypes

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

In [106]:
cafe['Quantity'].unique()

array(['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan], dtype=object)

In [107]:
cafe['Price Per Unit'].unique()

array(['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN'],
      dtype=object)

In [108]:
cafe['Total Spent'].unique()

array(['4.0', '12.0', 'ERROR', '10.0', '20.0', '9.0', '16.0', '15.0',
       '25.0', '8.0', '5.0', '3.0', '6.0', nan, 'UNKNOWN', '2.0', '1.0',
       '7.5', '4.5', '1.5'], dtype=object)

In [109]:
cafe['Quantity'] = pd.to_numeric(cafe['Quantity'],errors='coerce')

In [110]:
cafe['Price Per Unit'] = pd.to_numeric(cafe['Price Per Unit'],errors='coerce')

In [111]:
cafe['Total Spent'] = pd.to_numeric(cafe['Total Spent'],errors='coerce')

In [112]:
datatype_columns =['Quantity','Price Per Unit','Total Spent']

In [113]:
for i in datatype_columns:
    cafe[i] = pd.to_numeric(cafe[i],errors='coerce')

In [114]:
cafe.dtypes

Transaction ID       object
Item                 object
Quantity            float64
Price Per Unit      float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
dtype: object

In [115]:
cafe['Transaction Date'] = pd.to_datetime(cafe['Transaction Date'],errors='coerce')

In [116]:
cafe.dtypes

Transaction ID              object
Item                        object
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
dtype: object

In [117]:
cafe.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [118]:
cafe['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [119]:
cafe['Item'].replace({'UNKNOWN':'','ERROR':'','nan':''},inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_1164\2830791701.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cafe['Item'].replace({'UNKNOWN':'','ERROR':'','nan':''},inplace=True)


In [120]:
cafe['Quantity'].unique()

array([ 2.,  4.,  5.,  3.,  1., nan])

In [121]:
cafe['Price Per Unit'].unique()

array([2. , 3. , 1. , 5. , 4. , 1.5, nan])

In [122]:
cafe['Total Spent'].unique()

array([ 4. , 12. ,  nan, 10. , 20. ,  9. , 16. , 15. , 25. ,  8. ,  5. ,
        3. ,  6. ,  2. ,  1. ,  7.5,  4.5,  1.5])

In [123]:
cafe['Payment Method'].unique()

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan],
      dtype=object)

In [124]:
cafe['Payment Method'].replace({'UNKNOWN':np.nan,'ERROR':np.nan,},inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_1164\809661535.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cafe['Payment Method'].replace({'UNKNOWN':np.nan,'ERROR':np.nan,},inplace=True)


In [125]:
cafe['Payment Method'].unique()

array(['Credit Card', 'Cash', nan, 'Digital Wallet'], dtype=object)

In [126]:
cafe['Location'].unique()

array(['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR'], dtype=object)

In [127]:
cafe['Location'].replace({'UNKNOWN':np.nan,'ERROR':np.nan},inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_1164\2896724108.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cafe['Location'].replace({'UNKNOWN':np.nan,'ERROR':np.nan},inplace=True)


In [128]:
cafe['Location'].unique()

array(['Takeaway', 'In-store', nan], dtype=object)

In [129]:
cafe['Transaction Date'].unique()

<DatetimeArray>
['2023-09-08 00:00:00', '2023-05-16 00:00:00', '2023-07-19 00:00:00',
 '2023-04-27 00:00:00', '2023-06-11 00:00:00', '2023-03-31 00:00:00',
 '2023-10-06 00:00:00', '2023-10-28 00:00:00', '2023-07-28 00:00:00',
 '2023-12-31 00:00:00',
 ...
 '2023-08-01 00:00:00', '2023-01-20 00:00:00', '2023-11-11 00:00:00',
 '2023-02-13 00:00:00', '2023-07-30 00:00:00', '2023-02-17 00:00:00',
 '2023-05-20 00:00:00', '2023-11-05 00:00:00', '2023-03-27 00:00:00',
 '2023-07-03 00:00:00']
Length: 366, dtype: datetime64[ns]

In [130]:
list_temp = cafe['Transaction Date'].unique()

In [131]:
'ERROR' in list_temp 

False

In [132]:
cafe.isnull().sum()

Transaction ID         0
Item                 333
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [133]:
cafe.dropna(subset=['Total Spent'],inplace=True)

In [134]:
cafe.isnull().sum()

Transaction ID         0
Item                 322
Quantity             459
Price Per Unit       513
Total Spent            0
Payment Method      3008
Location            3757
Transaction Date     434
dtype: int64

In [135]:
cafe.drop(columns=['Payment Method'],inplace=True)

In [136]:
cafe.isnull().sum()

Transaction ID         0
Item                 322
Quantity             459
Price Per Unit       513
Total Spent            0
Location            3757
Transaction Date     434
dtype: int64

In [137]:
cafe.shape

(9498, 7)

In [138]:
cafe.dropna(subset=['Transaction Date'],inplace=True)

In [139]:
cafe.isnull().sum()

Transaction ID         0
Item                 304
Quantity             434
Price Per Unit       487
Total Spent            0
Location            3586
Transaction Date       0
dtype: int64

In [140]:
cafe['Item'].mode()

0    Coffee
Name: Item, dtype: object

In [141]:
cafe['Item'] = cafe['Item'].fillna(cafe['Item'].mode()[0])

In [142]:
cafe.isnull().sum()

Transaction ID         0
Item                   0
Quantity             434
Price Per Unit       487
Total Spent            0
Location            3586
Transaction Date       0
dtype: int64

In [143]:
cafe['Quantity'] = cafe['Quantity'].fillna(cafe['Quantity'].median())

In [144]:
cafe.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit       487
Total Spent            0
Location            3586
Transaction Date       0
dtype: int64

In [145]:
cafe['Price Per Unit'] = cafe['Price Per Unit'].fillna(cafe['Price Per Unit'].mean())

In [146]:
cafe.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent            0
Location            3586
Transaction Date       0
dtype: int64

In [147]:
cafe['Location'] = cafe['Location'].fillna('not specified')

In [148]:
cafe.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Location            0
Transaction Date    0
dtype: int64

In [149]:
cafe.head()

Transaction ID      Item  Quantity  Price Per Unit  Total Spent  \
0    TXN_1961373    Coffee       2.0             2.0          4.0   
1    TXN_4977031      Cake       4.0             3.0         12.0   
3    TXN_7034554     Salad       2.0             5.0         10.0   
4    TXN_3160411    Coffee       2.0             2.0          4.0   
5    TXN_2602893  Smoothie       5.0             4.0         20.0   

        Location Transaction Date  
0       Takeaway       2023-09-08  
1       In-store       2023-05-16  
3  not specified       2023-04-27  
4       In-store       2023-06-11  
5  not specified       2023-03-31

In [150]:
cafe[['del','Transaction ID']]=cafe['Transaction ID'].str.split('_',expand = True)

In [151]:
cafe

Transaction ID      Item  Quantity  Price Per Unit  Total Spent  \
0           1961373    Coffee       2.0        2.000000          4.0   
1           4977031      Cake       4.0        3.000000         12.0   
3           7034554     Salad       2.0        5.000000         10.0   
4           3160411    Coffee       2.0        2.000000          4.0   
5           2602893  Smoothie       5.0        4.000000         20.0   
...             ...       ...       ...             ...          ...   
9995        7672686    Coffee       2.0        2.000000          4.0   
9996        9659401    Coffee       3.0        2.947184          3.0   
9997        5255387    Coffee       4.0        2.000000          8.0   
9998        7695629    Cookie       3.0        2.947184          3.0   
9999        6170729  Sandwich       3.0        4.000000         12.0   

           Location Transaction Date  del  
0          Takeaway       2023-09-08  TXN  
1          In-store       2023-05-16  TXN  
3     not specified       2023-04-27  TXN  
4          In-store       2023-06-11  TXN  
5     not specified       2023-03-31  TXN  
...             ...              ...  ...  
9995  not specified       2023-08-30  TXN  
9996  not specified       2023-06-02  TXN  
9997  not specified       2023-03-02  TXN  
9998  not specified       2023-12-02  TXN  
9999       In-store       2023-11-07  TXN  

[9064 rows x 8 columns]

In [153]:
cafe = cafe[(cafe['Transaction Date']>='2023-01-01') & (cafe['Transaction Date']<='2023-06-30')]

In [154]:
cafe['Transaction Date'] = cafe['Transaction Date'].dt.strftime('%d/%m/%Y')

C:\Users\Admin\AppData\Local\Temp\ipykernel_1164\2373889362.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cafe['Transaction Date'] = cafe['Transaction Date'].dt.strftime('%d/%m/%Y')


In [155]:
cafe

Transaction ID      Item  Quantity  Price Per Unit  Total Spent  \
1           4977031      Cake       4.0        3.000000         12.0   
3           7034554     Salad       2.0        5.000000         10.0   
4           3160411    Coffee       2.0        2.000000          4.0   
5           2602893  Smoothie       5.0        4.000000         20.0   
12          7619095  Sandwich       2.0        4.000000          8.0   
...             ...       ...       ...             ...          ...   
9990        1538510    Coffee       5.0        2.000000         10.0   
9991        3897619  Sandwich       3.0        4.000000         12.0   
9994        7851634                 4.0        4.000000         16.0   
9996        9659401    Coffee       3.0        2.947184          3.0   
9997        5255387    Coffee       4.0        2.000000          8.0   

           Location Transaction Date  del  
1          In-store       16/05/2023  TXN  
3     not specified       27/04/2023  TXN  
4          In-store       11/06/2023  TXN  
5     not specified       31/03/2023  TXN  
12         In-store       03/05/2023  TXN  
...             ...              ...  ...  
9990  not specified       22/05/2023  TXN  
9991       Takeaway       24/02/2023  TXN  
9994  not specified       08/01/2023  TXN  
9996  not specified       02/06/2023  TXN  
9997  not specified       02/03/2023  TXN  

[4492 rows x 8 columns]

In [156]:
# cafe[(cafe['Transaction Date']>='2023-01-01') & (cafe['Transaction Date']<='2023-06-30')]

In [158]:
cafe.to_csv('cleandata1.csv')